// Automatically generated by MockGen. DO NOT EDIT!
// Source: interface.go

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Producer interface
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *_MockProducerRecorder
}

// Recorder for MockProducer (not exported)
type _MockProducerRecorder struct {
	mock *MockProducer
}

func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &_MockProducerRecorder{mock}
	return mock
}

func (_m *MockProducer) EXPECT() *_MockProducerRecorder {
	return _m.recorder
}

func (_m *MockProducer) New() string {
	ret := _m.ctrl.Call(_m, "New")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockProducerRecorder) New() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "New")
}
